### ISSUE TITLE
Docker container does not start dump1090 after upgrade to 7.2

### ISSUE THREAD

**Issue by jheinitz** [mikenye/docker-piaware#123]
Hello Team!

first of all, I would like to thank you for your efforts on this project. I'm running your piaware image on an old Dell Laptop for quite a while. I do regular updates of the image. The latest happed today. I upgraded from 7.1 to 7.2 and suddenly I could not send message to FlightAware. I logged into the container and figured out that there is no dump1090 process running. I performed a downgrade to 7.1 and everything works as expected. Any ideas?

Kind regards

Jens

**Comment by mikenye** [comment]
Hi @jheinitz, sorry you’re having trouble. 

Are you using `BEASTHOST` or is the piaware container talking to the SDR directly?

Could you please post the container logs (removing any sensitive info)?

Thanks.

**Comment by jheinitz** [comment]
Hello @mikenye ,

my container is talking directly to the USB device. Please find my logs below:

```
Attaching to piaware
piaware    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
piaware    | [s6-init] ensuring user provided files have correct perms...exited 0.
piaware    | [fix-attrs.d] applying ownership & permissions fixes...
piaware    | [fix-attrs.d] done.
piaware    | [cont-init.d] executing container initialization scripts...
piaware    | [cont-init.d] 00-libsecomp2: executing...
piaware    | [cont-init.d] 00-libsecomp2: exited 0.
piaware    | [cont-init.d] 01-piaware: executing...
piaware    | Set feeder-id to <my-feeder-id> in /etc/piaware.conf:1
piaware    | Set allow-auto-updates to no in /etc/piaware.conf:2
piaware    | Set allow-manual-updates to no in /etc/piaware.conf:3
piaware    | Set allow-mlat to yes in /etc/piaware.conf:4
piaware    | Set mlat-results to yes in /etc/piaware.conf:5
piaware    | Set receiver-type to rtlsdr in /etc/piaware.conf:6
piaware    | [cont-init.d] 01-piaware: exited 0.
piaware    | [cont-init.d] done.
piaware    | [services.d] starting services
piaware    | [skyaware] 2022/03/27 21:35:13 2022-03-27 21:35:13: server.c.1513) server started (lighttpd/1.4.59)
piaware    | [services.d] done.
piaware    | [piaware] 2022/03/27 21:35:13 ****************************************************
piaware    | [piaware] 2022/03/27 21:35:13 piaware version 7.2 is running, process ID 331
piaware    | [piaware] 2022/03/27 21:35:13 your system info is: Linux piaware 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux
piaware    | [piaware] 2022/03/27 21:35:15 Connecting to FlightAware adept server at piaware.flightaware.com/1200
piaware    | [piaware] 2022/03/27 21:35:19 no ADS-B data program seen listening on port 30005 for 6 seconds, next check in 60s
piaware    | [piaware] 2022/03/27 21:35:19 UAT support disabled by local configuration setting: uat-receiver-type
piaware    | [piaware] 2022/03/27 21:35:19 Connection with adept server at piaware.flightaware.com/1200 established
piaware    | [piaware] 2022/03/27 21:35:19 TLS handshake with adept server at piaware.flightaware.com/1200 completed
piaware    | [piaware] 2022/03/27 21:35:19 FlightAware server certificate validated
piaware    | [piaware] 2022/03/27 21:35:19 encrypted session established with FlightAware
piaware    | [piaware] 2022/03/27 21:35:19 adept reported location: 53.xxxxx, 9.xxxxx, 150ft AMSL
piaware    | [piaware] 2022/03/27 21:35:19 Receiver location changed, restarting dump1090 and skyaware978
piaware    | [piaware] 2022/03/27 21:35:19 attempting to restart dump1090..
piaware    | [piaware] 2022/03/27 21:35:19 has_invoke_rcd: Running on docker ignoring invoke-rc.d
piaware    | [piaware] 2022/03/27 21:35:19 has_invoke_rcd: Running on docker ignoring invoke-rc.d
piaware    | [piaware] 2022/03/27 21:35:19 attempting to restart dump1090 using '/etc/init.d/dump1090 restart < /dev/null &'...
piaware    | [piaware] 2022/03/27 21:35:19 dump1090 restart appears to have been successful
piaware    | [piaware] 2022/03/27 21:35:19 attempting to restart skyaware978..
piaware    | [piaware] 2022/03/27 21:35:19 can't restart skyaware978, no services that look like skyaware978 found
piaware    | [piaware] 2022/03/27 21:35:19 logged in to FlightAware as user <my-user>
piaware    | [piaware] 2022/03/27 21:35:19 my feeder ID is <my-feeder-id>
piaware    | [piaware] 2022/03/27 21:35:19 site statistics URL: https://flightaware.com/adsb/stats/user/<myuser>#stats-<id>
piaware    | [piaware] 2022/03/27 21:35:20 multilateration data requested
piaware    | [piaware] 2022/03/27 21:35:20 no ADS-B data program is serving on port 30005, not starting multilateration client yet
piaware    | [piaware] 2022/03/27 21:35:49 0 msgs recv'd from dump1090; 0 msgs sent to FlightAware
piaware    | [piaware] 2022/03/27 21:36:19 no ADS-B data program seen listening on port 30005 for 66 seconds, next check in 60s
piaware    | [piaware] 2022/03/27 21:36:20 no ADS-B data program is serving on port 30005, not starting multilateration client yet
piaware    | [piaware] 2022/03/27 21:37:19 no ADS-B data program seen listening on port 30005 for 126 seconds, next check in 60s
piaware    | [piaware] 2022/03/27 21:37:20 no ADS-B data program is serving on port 30005, not starting multilateration client yet
piaware    | [piaware] 2022/03/27 21:38:19 no ADS-B data program seen listening on port 30005 for 186 seconds, next check in 60s
piaware    | [piaware] 2022/03/27 21:38:20 no ADS-B data program is serving on port 30005, not starting multilateration client yet
piaware    | [piaware] 2022/03/27 21:39:19 no ADS-B data program seen listening on port 30005 for 246 seconds, next check in 60s
piaware    | [piaware] 2022/03/27 21:39:20 no ADS-B data program is serving on port 30005, not starting multilateration client yet
piaware    | [piaware] 2022/03/27 21:40:19 no ADS-B data program seen listening on port 30005 for 306 seconds, next check in 60s
piaware    | [piaware] 2022/03/27 21:40:20 no ADS-B data program is serving on port 30005, not starting multilateration client yet
piaware    | [piaware] 2022/03/27 21:40:49 0 msgs recv'd from dump1090 (0 in last 5m); 0 msgs sent to FlightAware
piaware    | [piaware] 2022/03/27 21:41:19 no ADS-B data program seen listening on port 30005 for 366 seconds, trying to start it...
piaware    | [piaware] 2022/03/27 21:41:19 attempting to start dump1090..
piaware    | [piaware] 2022/03/27 21:41:19 has_invoke_rcd: Running on docker ignoring invoke-rc.d
piaware    | [piaware] 2022/03/27 21:41:19 has_invoke_rcd: Running on docker ignoring invoke-rc.d
piaware    | [piaware] 2022/03/27 21:41:19 attempting to start dump1090 using '/etc/init.d/dump1090 start < /dev/null &'...
piaware    | [piaware] 2022/03/27 21:41:19 dump1090 start appears to have been successful
piaware    | [piaware] 2022/03/27 21:41:19 Usage: /etc/init.d/dump1090 {start|stop|restart|status}
piaware    | [piaware] 2022/03/27 21:41:20 no ADS-B data program is serving on port 30005, not starting multilateration client yet
piaware    | [piaware] 2022/03/27 21:41:24 child pid 375 exited with status 1
piaware    | [piaware] 2022/03/27 21:41:29 no ADS-B data program seen listening on port 30005 for 10 seconds, next check in 60s
piaware    | [piaware] 2022/03/27 21:42:20 no ADS-B data program is serving on port 30005, not starting multilateration client yet
piaware    | [piaware] 2022/03/27 21:42:29 no ADS-B data program seen listening on port 30005 for 70 seconds, next check in 60s
piaware    | [piaware] 2022/03/27 21:43:20 no ADS-B data program is serving on port 30005, not starting multilateration client yet
piaware    | [piaware] 2022/03/27 21:43:29 no ADS-B data program seen listening on port 30005 for 130 seconds, next check in 60s
piaware    | [piaware] 2022/03/27 21:44:20 no ADS-B data program is serving on port 30005, not starting multilateration client yet
piaware    | [piaware] 2022/03/27 21:44:29 no ADS-B data program seen listening on port 30005 for 190 seconds, next check in 60s

```

Here is my docker-compose.yml:
```
version: '2.1'

services:
  piaware:
    restart: always
    #image: ghcr.io/sdr-enthusiasts/docker-piaware:v7.1_nohealthcheck
    image: ghcr.io/sdr-enthusiasts/docker-piaware:latest
    tty: true
    container_name: piaware
    devices:
       - /dev/bus/usb:/dev/bus/usb
    ports:
      - 30003:30003
      - 30005:30005
    hostname: piaware
    networks:
      traefik-net:
        aliases:
          - piaware
    environment:
      - TZ=Europe/Berlin
      - LAT=53.xxxxx
      - LONG=9.xxxx
      - FEEDER_ID=<my-feeder-id>
      - RECEIVER_TYPE=rtlsdr
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.piaware.entrypoints=http"
      - "traefik.http.routers.piaware.rule=Host(`<external hostname>`)"
      - "traefik.http.middlewares.piaware-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.piaware.middlewares=piaware-https-redirect"
      - "traefik.http.routers.piaware-secure.entrypoints=https"
      - "traefik.http.routers.piaware-secure.rule=Host(`<external hostname>`)"
      - "traefik.http.routers.piaware-secure.tls=true"
      - "traefik.http.routers.piaware-secure.tls.certresolver=http"
      - "traefik.http.routers.piaware-secure.service=piaware"
      - "traefik.http.services.piaware.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_proxy"

networks:
  traefik-net:
    external: true
    name: traefik_proxy
```

When I use the tag `v7.1_nohealthcheck` instead of `latest`, everything works fine.

I hope that helps. Please let me know if you want me to do some extra tests. 

Kind regards

Jens
