### ISSUE TITLE
MLAT in relay mode #89 - error in implementation

### ISSUE THREAD

**Issue by SketchCND** [mikenye/docker-piaware#129]
### Closed issue " #MLAT in relay mode #89" has a bug in the implementation

The implemented code references "MLAT_RESULTS_BEASTHOST" where it should reference "MLAT_RESULTS_BEASTPORT". This causes issue if the MLAT_RESULTS_BEASTPORT environment variable is set. When not the default port of 30104 is used as intended.

### Part of my docker-compose and the relevant log from the piaware container

 ```
piaware:
    image: mikenye/piaware:latest
    tty: true
    container_name: piaware
    restart: always
    environment:
      - TZ="Europe/London"
      - LAT=51.xxxxx
      - LONG=-0.xxxx
      - RECEIVER_TYPE=relay
      - BEASTHOST=readsb
      - BEASTPORT=30005
      - ALLOW_MLAT=yes
      - MLAT_RESULTS=yes
      - MLAT_RESULTS_BEASTHOST=readsb
      - MLAT_RESULTS_BEASTPORT=30104
      - USERNAME=<redacted>
      - PASSWORD=<redacted>
      - FEEDER_ID=<redacted>
    tmpfs:
      - /run:exec,size=64M
      - /var/log
    links:
      - readsb
```

...
[piaware] 2022/04/21 10:21:58 multilateration data requested
[piaware] 2022/04/21 10:21:58 no ADS-B data program is serving on port 30005, not starting multilateration client yet
[piaware] 2022/04/21 10:21:58 no ADS-B data program seen listening on port 30005 for 3 seconds, next check in 60s
[piaware] 2022/04/21 10:21:58 UAT support disabled by local configuration setting: uat-receiver-type
[dump1090] 2022/04/21 10:22:03 Thu Apr 21 10:22:03 2022   dump1090-fa v7.2 starting up.
[dump1090] 2022/04/21 10:22:03 Net-only mode, no SDR device or file open.
[piaware] 2022/04/21 10:22:30 0 msgs recv'd from the ADS-B data program at readsb/30005; 0 msgs sent to FlightAware
[beast-splitter] 2022/04/21 10:22:55 127.0.0.1:30004: connected to 127.0.0.1:30004 with settings 
[beast-splitter] 2022/04/21 10:22:55 net(readsb:30005): configured with settings: BCdfGijk
[piaware] 2022/04/21 10:22:58 Starting multilateration client: /usr/lib/piaware/helpers/fa-mlat-client --input-connect localhost:30005 --input-type auto --results beast,connect,localhost:30104 --results beast,listen,30105 --results ext_basestation,listen,30106 **--results beast,connect,readsb:readsb** --udp-transport 206.253.80.200:11743:1875374332
[piaware] 2022/04/21 10:22:58 mlat-client(386): fa-mlat-client 0.2.12 starting up
[piaware] 2022/04/21 10:22:58 mlat-client(386): Using UDP transport to 206.253.80.200 port 11743
[piaware] 2022/04/21 10:22:58 mlat-client(386): Listening for Beast-format results connection on port 30105
[piaware] 2022/04/21 10:22:58 mlat-client(386): Listening for Extended Basestation-format results connection on port 30106
**[piaware] 2022/04/21 10:22:58 mlat-client(386): Warning: Ignoring bad results output option 'beast,connect,readsb:readsb': invalid literal for int() with base 10: 'readsb'**
[piaware] 2022/04/21 10:22:58 mlat-client(386): Route MTU changed to 1500
[piaware] 2022/04/21 10:22:58 mlat-client(386): Input connected to localhost:30005
...

### Problem code:

```
# If MLAT_RESULTS_BEAST_CONNECT is specified
if [[ -n "$MLAT_RESULTS_BEASTHOST" ]]; then
  piaware-config mlat-results-format "$(piaware-config -show mlat-results-format) beast,connect,${MLAT_RESULTS_BEASTHOST}:${MLAT_RESULTS_BEASTHOST:-30104}"
fi
```

### **Fix:** 

```
# If MLAT_RESULTS_BEAST_CONNECT is specified
if [[ -n "$MLAT_RESULTS_BEASTHOST" ]]; then
  piaware-config mlat-results-format "$(piaware-config -show mlat-results-format) beast,connect,${MLAT_RESULTS_BEASTHOST}:${MLAT_RESULTS_BEASTPORT:-30104}"
fi
```
